[package]
name = "edtf"
version = "0.1.0"
authors = ["Cormac Relf <web@cormacrelf.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
chrono = { version = "0.4", default-features = false, optional = true }
nom = { version = "6", default-features = false }

[dev-dependencies]
no-panic = "0.1.15"
